# 1. 繁體中文 (設為主要語言，權重 Weight 設為 1)
[zh-tw]
    languageName = '繁體中文'
    languageCode = 'zh-tw'
    contentDir = 'content/zh-tw'
    weight = 1
    title = '小波波律師事務所'
    disabled = false

    [zh-tw.params]
        description = "專注於民事訴訟與商務法律的專業律師團隊"
        copyright = "© 2026 小波波律師事務所"

# 2. 英文 (權重 Weight 設為 2，排在中文後面)
[en]
    languageName = 'English'
    languageCode = 'en-us'
    contentDir = 'content/en'
    weight = 2
    title = 'Bobo Law Firm'
    disabled = false

    [en.params]
        description = "Professional Legal Services"
        copyright = "© 2026 Bobo Law Firm"