[[main]]
  name = "About"
  identifier = "about"
  url = "/en/about/"
  weight = 1

[[main]]
  name = "Services"
  identifier = "services"
  url = "/en/services/"
  weight = 2

[[main]]
  name = "Contact"
  identifier = "contact"
  url = "/en/contact/"
  weight = 3